spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rbtmanager
    username: myuser
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

spring.security:
  user:
    name: admin
    password: admin123

mqtt:
  broker: tcp://localhost:1883
  client-id: rbt-manager